### PR TITLE
Truncate response body on cache hits

### LINKED ISSUE #54: Body is still sent on 304
There is odd behaviour around cache hits, the whole idea of the 304 status is to reduce data transmission if the browser/client has data which is still accurate. 

I've noticed that the response body isn't truncated defeating the purpose, technically this isn't a bug nor an implementation issue I still think it's incorrect behaviour.

While the developers can work around this by handling it in their projects, I feel like this package should handle this.

[RFC-9110](https://www.rfc-editor.org/rfc/rfc9110#name-304-not-modified)
[MDN 304](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304)

### PR DESCRIPTION
**Pull request by JimTools**
truncating the body to reduce data transmission on cache hits.

closes #54

### CODE REVIEW

File: src/Cache.php [hunk 1]
```diff
@@ -45,18 +47,28 @@ class Cache implements MiddlewareInterface
...
+    public function __construct(
+        StreamFactoryInterface $streamFactory,
+        string $type = 'private',
+        int $maxAge = 86400,
+        bool $mustRevalidate = false
+    ) {
         $this->type = $type;
         $this->maxAge = $maxAge;
         $this->mustRevalidate = $mustRevalidate;
+        $this->streamFactory = $streamFactory;
```
Comment (JimTools) [inline src/Cache.php:71]: Maybe for now it's better to add `slim/psr7` and call `StreamFactory` this would make it easier for anyone already using this package?

Comment (flavioheleno) [reply src/Cache.php:71]: I'd rather require `psr/http-factory` (and likely `psr/http-factory-implementation`) than `slim/psr7` as it keeps interoperable with other psr7 implementation packages

File: src/Cache.php [hunk 2]
```diff
@@ -11,9 +11,11 @@
 
 use Psr\Http\Message\ResponseInterface;
 use Psr\Http\Message\ServerRequestInterface;
+use Psr\Http\Message\StreamFactoryInterface;
 use Psr\Http\Server\MiddlewareInterface;
 use Psr\Http\Server\RequestHandlerInterface;
 
+use Slim\Psr7\Factory\StreamFactory;
```
Comment (odan) [inline src/Cache.php]: This dependency is not needed.

File: src/Cache.php (hunk 1 above)
Comment (odan) [reply src/Cache.php:71]: Only the user should decide which StreamFactoryInterface implementation should be used in their application.

Comment (JimTools) [reply src/Cache.php:71]: @flavioheleno @odan thank you for taken the time to review the PR I’ll update when I get some time.

**Comment by odan** [comment]
I've been thinking about this approach. Wouldn't it be easier to implement a custom middleware that checks the response for status code 304 and, if the case, returns a response with an empty body. The advantage would be that this can be added when needed and doesn't break the existing logic.

**Comment by flavioheleno** [comment]
Honestly, dropping the body is something that I'd expect from this middleware and not have to add another one to handle it.
IMHO, the current behavior/logic is broken.

**Comment by akrabat** [comment]
I've updated to make the `StreamFactory` optional which keeps BC with current implementations. Also merged in the latest 1.x branch.

File: tests/CacheTest.php [hunk 3]
```diff
@@ -16,11 +16,18 @@
 use Slim\Psr7\Factory\ResponseFactory;
 use Slim\Psr7\Factory\ServerRequestFactory;
 
+use Slim\Psr7\Factory\StreamFactory;
 use function gmdate;
 use function time;
 
 class CacheTest extends TestCase
 {
+    private function createCache(string $type, int $maxAge, bool $mustRevalidate, bool $withStreamFactory): Cache
```
Comment (odan) [inline tests/CacheTest.php]: Private methods should come after public methods.

Comment (akrabat) [reply tests/CacheTest.php]: I tend to like test helper methods at the top, but I'm not precious about it.
Moved.

**Review by odan — APPROVED** [review]
